
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WHERE = 5;
  public static final int FROM = 4;
  public static final int AND = 7;
  public static final int SELECT = 2;
  public static final int RPAREN = 14;
  public static final int SEMI = 10;
  public static final int IN = 6;
  public static final int APOST = 15;
  public static final int NOT = 8;
  public static final int PERIOD = 12;
  public static final int GREATER = 19;
  public static final int NAME = 16;
  public static final int LPAREN = 13;
  public static final int EQUALS = 18;
  public static final int COMMA = 11;
  public static final int EOF = 0;
  public static final int DISTINCT = 3;
  public static final int error = 1;
  public static final int EXISTS = 9;
  public static final int LESSER = 20;
  public static final int INTNUM = 17;
  public static final int EQGREATER = 21;
  public static final int EQLESSER = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SELECT",
  "DISTINCT",
  "FROM",
  "WHERE",
  "IN",
  "AND",
  "NOT",
  "EXISTS",
  "SEMI",
  "COMMA",
  "PERIOD",
  "LPAREN",
  "RPAREN",
  "APOST",
  "NAME",
  "INTNUM",
  "EQUALS",
  "GREATER",
  "LESSER",
  "EQGREATER",
  "EQLESSER"
  };
}

